server:
  port: 5555

spring:
  application:
    name: gateway-server
    loadbalancer:
      ribbon:
        enabled: false
  cloud:
    discovery:
      enabled: true
    gateway:
      gdefault-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: ms-products
          uri: lb://ms-products
          predicates:
            - Path=/api/*/products/**
#            - Path=/products/**
#          filters:
#            - StripPrefix=1
        - id: ms-orders
          uri: lb://ms-orders
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
