server:
  port: 8080

spring:
  application:
    name: gateway-server
    loadbalancer:
      ribbon:
        enabled: false
  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: ms-products
          uri: lb://ms-products
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
        - id: ms-orders
          uri: lb://ms-orders
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
