server:
  port: 8191
#  servlet:
#    context-path: /shop
spring:
  application:
    name: ms-auth
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:market_auth_db;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

jwt:
  secret: sadfljhasdruywtqkjyfgsjfbagjksfajlsdgfjk
